DROP TABLE IF EXISTS USUARIO;
CREATE TABLE USUARIO(
TELEGRAM_ID INTEGER PRIMARY KEY,
NOME TEXT
);

DROP TABLE IF EXISTS MENSAGEM;
CREATE TABLE MENSAGEM(
NUMERO INTEGER PRIMARY KEY ASC,
TEXTO TEXT NOT NULL,
USUARIO INTEGER,
FOREIGN KEY(USUARIO) REFERENCES USUARIO(TELEGRAM_ID)
);